### ISSUE TITLE
How to get Galaxy Brain Badge

### ISSUE THREAD

**Issue by Settasit68** [gomzyakov/achievements#52]
As it is now unable to get via community discussion, how to get it?

**Comment by davevad93** [comment]
Hey @Settasit68 , that badge can still be earned via other discussions, there are many repos on GitHub with open discussions but you have to dig around to find them.

**Comment by mahin2406** [comment]
You can earn by commenting in community and if 2 or more people accept your comment than you get it
Thanks:)

**Comment by gomzyakov** [comment]
Hi guys!

If you want, you can create a couple of discussions here https://github.com/orgs/github-profile-achievements/discussions and experiment with getting a badge.

**Comment by gomzyakov** [comment]
@Settasit68 Hello!

Can you close this issue? Or is the issue still relevant?

**Comment by ssakuraki** [comment]
good
