### ISSUE TITLE
Replace "stars"-image to links to githubusercontent.com & delete `images` folder

### ISSUE THREAD

**Issue by gomzyakov** [gomzyakov/achievements#69]
```
[stars-dark]: images/stars-dark.svg#gh-dark-mode-only
[stars-light]: images/stars-light.svg#gh-light-mode-only
```

**Comment by KiLig-bo** [comment]
Kindly to ask if there is somebody working for this issue? If not ,I'm glad to undertake it.
/cc @gomzyakov

**Comment by gomzyakov** [comment]
@KiLig-bo Hi! 

No one has started this шыыгу yet. I have assigned it to you ;)

**Comment by KiLig-bo** [comment]
Hello, I’m pleased to inform you that I have completed the task and submitted a PR. Please approve it.
/cc @gomzyakov
