### ISSUE TITLE
Correct the names of languages ​​"Traditional chinese" and "Chinese" to the original spelling 

### ISSUE THREAD

**Issue by gomzyakov** [gomzyakov/achievements#81]
In this section:

<img width="825" alt="image" src="https://github.com/user-attachments/assets/72dec75d-f842-46ec-9453-fda30ccb0cd6">

**Comment by gomzyakov** [comment]
Can someone check the spelling?

**Comment by ridemountainpig** [comment]
I think the Quickdraw content in Traditional Chinese can be changed like this to make it better.
```
在開啟後 5 分鐘內關閉問題或拉取請
```
 ⬇️ change to ⬇️
```
在 PR 開啟 **5 分鐘內**關閉 PR
```

**Comment by gomzyakov** [comment]
@ridemountainpig Hello! Can you make a PR?

**Comment by ridemountainpig** [comment]
> @ridemountainpig Hello! Can you make a PR?

No problem 😊
