### ISSUE TITLE
Heart On Your Sleeve

### ISSUE THREAD

**Issue by AlgorithmAlchemy** [gomzyakov/achievements#87]
As soon as I don't like the achievement doesn't work! Either update that it doesn’t work or give instructions on how to get it! Likes Issues
  did not give results

**Comment by matheusbarzon** [comment]
Hi there. 
It's "work", but not to everyone.
How about changing 'Being tested' to 'Being Tested - unable to earn'?

https://github.com/orgs/community/discussions/43514

**Comment by gomzyakov** [comment]
@matheusbarzon Hi!

Yes, it needs to be replaced. Can you make a PR with corrections?

**Comment by AlgorithmAlchemy** [comment]
> @matheusbarzon Hi!
> 
> Yes, it needs to be replaced. Can you make a PR with corrections?

Hello
If anything, I am also ready to participate
